[database]
host = "db"
port = 5432
name = "ergo"
user = "ergo"
pw = "ergo"
bootstrapping_work_mem_kb = 128000

[node]
url = "http://node:9053"
poll_interval = 5 # seconds

[repairs]
# Trigger a repair event every 1000 blocks
interval = 1000 # blocks
# Wait 5 blocks after a trigger height before starting a repair event.
# This is to reduce the chance of including non-main chain blocks in
# a repair event.
offset = 5 # blocks

[coingecko]
url = "https://api.coingecko.com/api/v3/coins/ergo/market_chart/range"
# Time to wait between consecutive requests
interval = 0.2 # seconds
