[database]
host = "db"
port = 5432
name = "ergo"
user = "ergo"
pw = "ergo"
bootstrapping_work_mem_kb = 128000

[node]
url = "http://node:9053"
poll_interval = 5 # seconds

[deposits]
# Minimum number of blocks to be processed in a batch
interval = 10 # blocks
# Number of blocks from latest one to exclude from processing batch.
# This is to reduce the chance of processing a fork.
buffer = 5 # blocks

[coingecko]
url = "https://api.coingecko.com/api/v3/coins/ergo/market_chart/range"
# Time to wait between consecutive requests
interval = 0.2 # seconds
