[package]
name = "ew"
version = "0.1.0"
edition = "2021"

[dependencies]
base16 = "0.2.1"
ergotree-ir = "0.22.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# serde_yaml = "0.9.16"
thiserror = "1.0"
tokio = {version = "1", features = ["full"]}
tokio-postgres = {version = "0.7.8", features=["with-serde_json-1"]}
tracing = "0.1"
tracing-subscriber = "0.3"


[dev-dependencies]
axum = {version = "0.6", features = ["query"]}
pretty_assertions = "1.3.0"

