[database]
host = "localhost"
port = 5432
name = "db"
user = "user"
pw = "hello"

[node]
url = "http://127.0.0.1:9053"
poll_interval = 5 # seconds

[cexs]
deposit_processing_interval = 500 # blocks
deposit_processing_offset = 10 # blocks

