[database]
host = "localhost"
port = 5432
name = "db"
user = "user"
pw = "hello"
bootstrapping_work_mem_kb = 128000

[node]
url = "http://127.0.0.1:9053"
poll_interval = 5 # seconds

[deposits]
# Minimum number of blocks to be processed in a batch
interval = 10 # blocks
# Number of blocks from latest one to exclude from processing batch.
# This is to reduce the chance of processing a fork.
buffer = 5 # blocks

[coingecko]
url = "https://api.coingecko.com/api/v3/coins/ergo/market_chart/range"
# Time to wait between consecutive requests
interval = 0.2 # seconds
